version: '3.6'

services:
  redis:
    image: redis:4-alpine
    volumes:
      - app-redis:/var/lib/redis/data
  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    command: bundle exec sidekiq
    volumes:
      - '.:/project'
    env_file:
      - '.env'
  web:
    build: .
    volumes:
      - '.:/project'
    working_dir: /project
    command: puma
    ports:
      - 3000:3000
    depends_on:
      - db
      - sidekiq
      - redis
    stdin_open: true
    tty: true
    env_file:
      - .env
  db:
    image: postgres:10.3-alpine
    env_file:
      - .env
    ports:
        - "5432:5432"

volumes:
  app-db:
  app-redis: